name: Structure Check
on: [push, pull_request]
jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Required Directories
        run: |
          if [! -d "models" ]; then echo "Missing models directory"; exit 1; fi
          if [! -d "results"]; then echo "Missing results directory"; exit 1; fi
